// Poseidon2 Circuit Template for BN254
// ======================================
// This file will contain the full Poseidon2 permutation implementation
// with exact parameters matched to Soroban's native poseidon2_hash.
//
// DO NOT use circomlib's Poseidon() — that is Poseidon V1 (CVE-2026-32129).
//
// Parameters from: rs-soroban-poseidon/src/poseidon2/params.rs
// - S-box: x^5
// - Full rounds: 8 (4 + 4)
// - Partial rounds: 56
// - Total rounds: 64
//
// Supported state widths: t=2 (rate 1), t=3 (rate 2), t=4 (rate 3)
//
// The round constants will be generated by scripts/generate-circom-params.js
// from the hex values in params.rs, converted to decimal for Circom.
//
// TODO: Sprint 1 — implement full Poseidon2 permutation template

pragma circom 2.1.0;

// Placeholder — actual implementation in Sprint 1
// template Poseidon2Permutation(t) { ... }
// template Poseidon2Hash(nInputs) { ... }
