// @generated by circuits/scripts/gen_verifier_fixture.mjs — DO NOT EDIT BY HAND.
//
// A REAL Groth16 proof for withdraw_v2, with its verification key and public
// inputs, in the exact byte layout Groth16VerifierContract::verify consumes:
//   G1 = x ‖ y                     (2 × 32-byte big-endian)
//   G2 = x_c1 ‖ x_c0 ‖ y_c1 ‖ y_c0 (4 × 32-byte big-endian, c1 first)
// A/B/C are unnegated; the contract negates alpha, vk_x and C itself.
//
// Statement proved: possession of the secret for a 1-XLM note at index 0 of an
// otherwise-empty tree, bound to a withdraw recipient.
//   public inputs = [root, nullifier, withdraw_binding]
//
// Regenerate after ANY change to withdraw_v2.circom, lib/note.circom,
// lib/babyjubjub.circom, or the phase-2 setup:
//     cd circuits && node scripts/gen_verifier_fixture.mjs

pub const PROOF_A: &str = "040aa10110ad1cd775a13f2970e663668250e2cdb512cff696542b4b72492ce41a3c5635df18fb76cd6df9c934a89138f333d551f65a2e5a0507ecfb79bf3d9a";
pub const PROOF_B: &str = "255a4ff0073d29cbc2b4c14020234fdb388087ba4214739fb437e6d5ca0e77d62aa9211b3e041e7feda58f897d1cec8e0de34b565d33e1519578769436483bd327e5e1c19cde1e62c16de1588184984ba54fbe5ad4e9e77aac924dac2e8476d11a36ab071272513cd4d952c5b73bfc6724e8c0231463ced8a3ef3f5860d2073c";
pub const PROOF_C: &str = "28209bffed0f1a030cae7cf2922ad12511cc63f1cef7f2750e56194b26d3436c110b6ae851b0779341a5d5b68b11520fa6e9f036a71deadf0885860dc53c402d";

pub const PUBLIC_INPUTS: [&str; 3] = [
    "22effed6ee994a5940b6e616bf1b2280b4f40e060d899c38279acfbee6af3304",
    "05c219ff25fbd4abe62a51c06c81279b5fdb3932b703f098b8a395890814a362",
    "000000000000000000000000000000000000000000000000000000003ade68b1",
];

pub const VK_ALPHA_G1: &str = "180544e244bb73aa9e3582da030bbbe8f941612c19372267210d7e8abde533ef106352764132dca8eca50873d4e68fe7791fde88eddca237e6217a4510961f9b";
pub const VK_BETA_G2: &str = "1292ce556a7de72981b9d772ac01ee8fb60e1954c3b289b224e55e74e0ab77b72c990820e4f02583fc6f64922e12f63d9118eba3c71dfe2fea0ecb7107c66a55150137799119e80110cc98877648ea527d52b0781ca03a4f6b3c4d75f56ed8c02708b12d830f4dc237e3075123562f68eddb2047a727362331b218f3f8c22bce";
pub const VK_GAMMA_G2: &str = "198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa";
pub const VK_DELTA_G2: &str = "25b90ae49f091498107e6d006742911415371f1dab2cc4b323a6f32fc6e830390c0836c70e8ce0cc94d25564f471a976c76140628689b770cd7b6fd3a0eb943e02874c645baeb9ef74563a081589b72b10d83771aba5d177edc68a0b07be50442a2e2d58a47449c005203ccf410546635ff11691f9f29a453a3760cf61a098e6";

pub const VK_IC: [&str; 4] = [
    "2854dff2e076a03d0b153d52393c1c3757f7475396478afaeb0960529770ad0a127b31d41f46b92bf37acbcdbfe865ce8b30ae23123ffe8fd4fa5b2bd4f1536a",
    "2e2fbcb1d7464f98fad58840cb85140a90d75cea495c15f4af30a399d218afb4297d056bcb7f1ce60697763c0fbefecb8268da6e9a63f4b6d7c607bcbff0a00f",
    "0575cd484addb8feb8778579f0ce061687d468be57adfcb7337512b487d0f07c0ce3e2a8d3189b6d19ee757dc375e6403bfc5203eaadf4ac7ad9660977b29c0f",
    "301851242c8d18a62d04fd54ae37630a4c7e63dea4c06bd4ae01bec3d777e1492f340d354be3b96db84a80e8202c40d3ec32230bff115607a081701aef5454d1",
];
