// @generated by circuits/scripts/gen_verifier_fixture.mjs — DO NOT EDIT BY HAND.
//
// A REAL Groth16 proof for transfer_v2, with its verification key and public
// inputs, in the exact byte layout Groth16VerifierContract::verify consumes:
//   G1 = x ‖ y                     (2 × 32-byte big-endian)
//   G2 = x_c1 ‖ x_c0 ‖ y_c1 ‖ y_c0 (4 × 32-byte big-endian, c1 first)
// A/B/C are unnegated; the contract negates alpha, vk_x and C itself.
//
// Statement proved: spending a 1-XLM note at index 0 of an otherwise-empty tree
// and creating a 1-XLM note for a recipient, bound to the sender's ephemeral point.
//   public inputs = [root, nullifier, commitment_out, ephemeral_x, ephemeral_y]
//
// Regenerate after ANY change to transfer_v2.circom, lib/note.circom,
// lib/babyjubjub.circom, or the phase-2 setup:
//     cd circuits && node scripts/gen_verifier_fixture.mjs --circuit transfer_v2

pub const PROOF_A: &str = "01c21bdb09ecbc1e0fe4abf0ab6fee42926432d78b206068695607a4042e8c0d10bb1bed9b343cbc02cb355df1b77d1ffd4886472c5537ac77003e748914cd1d";
pub const PROOF_B: &str = "125c8685177202da1f6ba26b2b008de89bddf38798f9e760d82728cee8bdfeef17ff2ec2efb4b75c6e4c97cccdda16bde217695dcacf7adb3947c48d6b036dc12c85230eed4ff99ad75403f16b4d84fc460fc1ec606a07b6789d64451044d7663049e7cd98533d4fc85b6181fbea2b054185a732ff84062a749356ee9e6b6130";
pub const PROOF_C: &str = "199a5e30fc1d1867dd8f541f2c00b9eedf2195b26602c49f12c6fe57662c1bb4245ea43c7d4ee3574bdf51b53e32336f20eba038ddb7a93a50740a96e1c417b0";

pub const PUBLIC_INPUTS: [&str; 5] = [
    "22effed6ee994a5940b6e616bf1b2280b4f40e060d899c38279acfbee6af3304",
    "05c219ff25fbd4abe62a51c06c81279b5fdb3932b703f098b8a395890814a362",
    "07608357d40c54f83f7278a9c624d55b4114074f3bff27ee39a56e145e4cc89b",
    "2a39f6a9afe8c569977ec299af985e30142d18ee451008ffd13fc0a2a36cf54e",
    "1d5a43dc73fe0493cce521cc92a4d34d4837214ce47871c587c567d2d0c72c8f",
];

pub const VK_ALPHA_G1: &str = "180544e244bb73aa9e3582da030bbbe8f941612c19372267210d7e8abde533ef106352764132dca8eca50873d4e68fe7791fde88eddca237e6217a4510961f9b";
pub const VK_BETA_G2: &str = "1292ce556a7de72981b9d772ac01ee8fb60e1954c3b289b224e55e74e0ab77b72c990820e4f02583fc6f64922e12f63d9118eba3c71dfe2fea0ecb7107c66a55150137799119e80110cc98877648ea527d52b0781ca03a4f6b3c4d75f56ed8c02708b12d830f4dc237e3075123562f68eddb2047a727362331b218f3f8c22bce";
pub const VK_GAMMA_G2: &str = "198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa";
pub const VK_DELTA_G2: &str = "1bf5373849fdb84751e42ecae86f8c74c0f8f1cbca00dff2a38e08322a4707102771e49424555f3ec98a6b378ea2969a225c9c2b308ecbe242294e2b73de394c0118a3a4973ae720bb315c74c1ad44b407b5d92931c2ee56d89abc30d78a5f0719c5fdcab9f3d03421e6914094a7417e144d5c745cfe6c1ff8cbf534df2aa591";

pub const VK_IC: [&str; 6] = [
    "0f7c0e6fc50b225d5488c8dfec194c00524b23d3da58147ccc90152c6809b6e32ecafb02aecb1e87627ea5b5f7f774294e0ef2d0e73636141b18b536a14f2268",
    "01a4251956b3f2b610717aa0ba09f45939ac819947ca1124256a2ea41043b8b20c091420099e65aff2b0ac305c1071e5a033c1d55f4266c43c9bc16baf3d9a65",
    "259387b35a90ff12425625b0061e6dbf9e4a435e0505bdf9686e7c1ad21e122710a3fe828115a8905adc38804475ad355a463640e2e9d022cddd831359d910cb",
    "0df89ed88493de2b4b598f7620d3a5ac111fad8057c108d4bd925e747cfdb50b09e14db4809ce63155e221bfe008eebe214005511dc1af7aef509429099d2574",
    "2cc641c6adc0199694261708c26625a9964c02728c798d9b1bd5b5869ac13a261f36bafdaa10df052448850b55443b9759a43eb620eabb824077baef048df339",
    "05d05f2059183652b571047a341026a8ff62f1c6cb4a68ae6b030a828251d05d0a84f3791cade46ef63856dd770d32ef6029a3d50b9f419f2767b4fd74ae2f73",
];
