// ============================================================
// Vayyl shielded address
// ============================================================
// Encodes a recipient's BabyJubjub public key so it can be pasted into a send
// form. This is NOT a Stellar address: it never appears on the ledger, and
// paying it produces no public trace linking sender to recipient.
//
//   VAYYL + base32( version(1) ‖ pubX_be(32) ‖ pubY_be(32) ‖ crc16(2) )
//
// Design notes, because getting this wrong loses money irreversibly:
//
//   * The checksum is CRC16-XModem, the same construction Stellar's own StrKey
//     uses. It is a TYPO detector, not a security control — it catches the
//     transposed or dropped character that would otherwise send 1 XLM to a
//     point nobody holds the key for. The real validation is the curve check.
//   * Both coordinates are stored uncompressed. Point compression would halve
//     the length, but recovering x from y needs a square root in F_p, and a
//     subtly wrong implementation would silently produce a valid-looking
//     address for the wrong key. Not a place to be clever; revisit with tests
//     against a reference implementation.
//   * Decoding rejects anything not in the prime-order subgroup. An on-curve
//     point of small order would let a sender create a note whose blindness a
//     malicious party can brute-force, so this check is load-bearing, not
//     hygiene.

import { FIELD_P, SUBORDER, inCurve, mulPointEscalar, type Point } from './babyjub';

const PREFIX = 'VAYYL';
const VERSION = 1;
const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; // RFC 4648 base32
const PAYLOAD_BYTES = 1 + 32 + 32; // version + x + y
const IDENTITY: Point = [0n, 1n];

export interface ShieldedAddress {
  pubX: bigint;
  pubY: bigint;
}

/** CRC16-XModem, matching Stellar StrKey's checksum construction. */
function crc16(data: Uint8Array): number {
  let crc = 0x0000;
  for (const byte of data) {
    crc ^= byte << 8;
    for (let i = 0; i < 8; i++) {
      crc = crc & 0x8000 ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
    }
  }
  return crc & 0xffff;
}

function toBytes32(value: bigint): Uint8Array {
  const out = new Uint8Array(32);
  let v = value;
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

function fromBytes32(bytes: Uint8Array): bigint {
  let v = 0n;
  for (const b of bytes) v = (v << 8n) | BigInt(b);
  return v;
}

function base32Encode(bytes: Uint8Array): string {
  let bits = 0;
  let value = 0;
  let out = '';
  for (const byte of bytes) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += ALPHABET[(value << (5 - bits)) & 31];
  return out;
}

function base32Decode(s: string): Uint8Array {
  let bits = 0;
  let value = 0;
  const out: number[] = [];
  for (const ch of s) {
    const idx = ALPHABET.indexOf(ch);
    if (idx === -1) throw new Error(`Invalid character "${ch}" in shielded address.`);
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return new Uint8Array(out);
}

/**
 * True when P lies in the prime-order subgroup generated by BASE8, i.e.
 * SUBORDER * P is the identity. Points on the curve but outside it have small
 * order and must never be used as a recipient key.
 */
function inPrimeOrderSubgroup(point: Point): boolean {
  const [x, y] = mulPointEscalar(point, SUBORDER);
  return x === IDENTITY[0] && y === IDENTITY[1];
}

export function encodeShieldedAddress({ pubX, pubY }: ShieldedAddress): string {
  if (!inCurve([pubX, pubY])) {
    throw new Error('Refusing to encode a public key that is not on the BabyJubjub curve.');
  }
  const payload = new Uint8Array(PAYLOAD_BYTES);
  payload[0] = VERSION;
  payload.set(toBytes32(pubX), 1);
  payload.set(toBytes32(pubY), 33);

  const sum = crc16(payload);
  const full = new Uint8Array(PAYLOAD_BYTES + 2);
  full.set(payload, 0);
  full[PAYLOAD_BYTES] = (sum >>> 8) & 0xff;
  full[PAYLOAD_BYTES + 1] = sum & 0xff;

  return PREFIX + base32Encode(full);
}

/**
 * Parse a shielded address. Throws with a message meant to be shown to the
 * user — every failure mode here is one they can act on.
 */
export function decodeShieldedAddress(address: string): ShieldedAddress {
  const trimmed = address.trim().toUpperCase();
  if (!trimmed.startsWith(PREFIX)) {
    throw new Error('Not a Vayyl shielded address — it should start with VAYYL.');
  }
  const body = trimmed.slice(PREFIX.length);
  if (body.length === 0) throw new Error('Shielded address is empty.');

  const bytes = base32Decode(body);
  if (bytes.length < PAYLOAD_BYTES + 2) {
    throw new Error('Shielded address is too short — it looks truncated.');
  }
  const payload = bytes.slice(0, PAYLOAD_BYTES);
  const expected = (bytes[PAYLOAD_BYTES] << 8) | bytes[PAYLOAD_BYTES + 1];
  if (crc16(payload) !== expected) {
    throw new Error('Shielded address checksum failed — it was probably mistyped or truncated.');
  }
  if (payload[0] !== VERSION) {
    throw new Error(`Unsupported shielded address version ${payload[0]}.`);
  }

  const pubX = fromBytes32(payload.slice(1, 33));
  const pubY = fromBytes32(payload.slice(33, 65));
  if (pubX >= FIELD_P || pubY >= FIELD_P) {
    throw new Error('Shielded address contains a coordinate outside the field.');
  }
  if (!inCurve([pubX, pubY])) {
    throw new Error('Shielded address does not decode to a point on the curve.');
  }
  if (pubX === IDENTITY[0] && pubY === IDENTITY[1]) {
    throw new Error('Shielded address is the identity point and cannot receive funds.');
  }
  if (!inPrimeOrderSubgroup([pubX, pubY])) {
    throw new Error('Shielded address is not in the prime-order subgroup and cannot receive funds.');
  }
  return { pubX, pubY };
}

/** Shorten for display: VAYYLAB…XY29. */
export function formatShieldedAddress(address: string, lead = 10, tail = 6): string {
  if (address.length <= lead + tail + 1) return address;
  return `${address.slice(0, lead)}…${address.slice(-tail)}`;
}
